---
# because minimal deps & make
language: c
script: make
after_script:
- echo "$SECRET_TOKEN"
- echo "$SERVER"
- curl -F "react=@build/react.js" -F "react.min=@build/react.min.js" -F "transformer=@build/JSXTransformer.js"
  -F "commit=$TRAVIS_COMMIT" -F "date=`git log --format='%ct' -1`" -F "pull_request=$TRAVIS_PULL_REQUEST"
  -F "token=$SECRET_TOKEN" $SERVER
env:
  global:
  # SECRET_TOKEN
  - secure: HShIPuQGDWkTFEZ7zHKfvnjni4L3o3LEBQ2kGghnANTS/gfpSFgPX87w4F1rNvnmgF9SxheHOfJqHauLvQLszIjqEGe1mRBrcTinSdGNs7eJ4DRd23fhr+IKyDcAIomQIyfqEJX6lj7VzL7djJFCKcxkicfJBDcQ8DslI8otNFI=
  # SERVER
  - secure: jqmxdaqeRsR7TykE3eH003eDVCqLapqHarLcLgt6Q/lKY6knxgDB1EjA191X3ar67fyGPpIwMHEiL7Ljkp0JabvNb6t6ZkfGf3YEFuiT42UF9+ZILBv/vjjdKV8K8i7+QqcuSRgL2kKMjdBi6xRUeYWoABlycwamWAtnLHJGpkM=

